### ISSUE TITLE
Bug fix requests for Enemy Editors

### ISSUE THREAD

**Issue by Reveraine** [bleehu/CXDocs#14]
1. An enemy with abilities attached cannot be deleted. The error page comes up.

2. "New mapping not valid. Could not add." Error Appears in the ability editor, even though everything seems to be functioning properly.

3. All new enemies seem to be printed at Level 5, regardless of the entry in the text box. 

4. Once assigned to an enemy, Abilities cannot be deleted: Error page appears.

**Comment by bleehu** [comment]
I believe Issue 1 has been fixed. 
I believe Issue 4 has been fixed.

**Comment by bleehu** [comment]
Issue 2 in RC. Not released yet.

**Comment by bleehu** [comment]
I think this is all fixed and released. If issues still persist, please open separate tickets for each issue. =)
