### ISSUE TITLE
Gripe: Re-update CXDocs Weapons

### ISSUE THREAD

**Issue by rosebrallier** [bleehu/CXDocs#157]

**Comment by bleehu** [comment]
@rosebrallier, do you remember what was missing here? Was it automatic/burst penalties for weapons?

**Comment by rosebrallier** [comment]
I remember that some were missing APLs?

Rose Brallier

**Comment by Turtlelord26** [comment]
APL, autofire penalties, reload DCs and times.

**Comment by bleehu** [comment]
Updated in production! 
https://www.compoundx.org/monsterweapons#top
