### ISSUE TITLE
HTML tutorial 1: Select boxes

### ISSUE THREAD

**Issue by bleehu** [bleehu/CXDocs#21]
The first thing we need to start the character creator project is the HTML form that the user will use to actually do the creation. @Masterdiekillsu has the start of one, but hasn't uploaded it. And the one that he has doesn't have a select box for choosing race or class. 

Look at https://github.com/bleehu/CXDocs/blob/master/templates/player_characters.html#L1-L32 for an example of how to use a template that extends the existing layout which will do a lot of the boring work like CSS for you. I would actually start with a copy, change the title and and then make the HTML form in the body. 

use https://www.w3schools.com/html/html_forms.asp and https://www.w3schools.com/tags/tag_select.asp to learn how to make select boxes. Don't worry about where to send the action to for now; creating that endpoint and the backend logic will be my job. 

Clone down the project, branch off of master then make the new template in the CXDocs/templates/  folder. Maybe call it character_creator.html? 

then click the green button here to make a pull request and assign me as the reviewer. https://github.com/bleehu/CXDocs/pulls

- [ ] clone the repository from the website to your work machine
- [ ] make a new branch using `$git branch <branchname>`
- [ ] make the new template in CXDocs/templates (start with a copy of playercharacters.html)
- [ ] change the view characters page to a create characters page with notepad++. Changes only need to be a select box with all of the races, and a second select box with all of the classes. 
- [ ] `git commit` your changes (you may need to use `git add` first)
- [ ] `git push origin <your branch name>` to push the changes to the website
- [ ] make the pull request
- [ ] brag about what an awesome developer you are whilst I praise your glory in my review

**Comment by bleehu** [comment]
It looks like we may have to do this from scratch

**Comment by Wildlovelies** [comment]
pull request #67

**Comment by bleehu** [comment]
PR merged. I don't know why it's not referencing it. but there ya go.
