### ISSUE TITLE
Feature Request: How To General

### ISSUE THREAD

**Issue by Turtlelord26** [bleehu/CXDocs#65]
@bleehu 
With the requested proliferation of howto pages, I would propose moving the more general points in How to Enemy Weapons to a separate document (along with more generalized wording i.e. 'item' instead of 'weapon'). That way, we neither have to repeat those points in other howtos nor have How To Weapons be twice as long as the rest.
I refer specifically to the sections Power Curve, Differences in Kind, Telegraphing, and Cost.

**Comment by bleehu** [comment]
I think this is a great idea!

**Comment by bleehu** [comment]
Pushed directly to master in commit 48f3cfe.
